{{- if .Values.mysql.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.mysql.persistence.claimName }}
    namespace: {{ .Values.namespace.name }}
    labels:
        {{- include "php-app.labels" . | nindent 6 }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.mysql.persistence.size }}
{{- end -}}