apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secret.name }}
    namespace: {{ .Values.namespace.name }}
    labels: 
        {{- include "php-app.labels" . | nindent 6 }}
type: Opaque
stringData:
    #for MYSQL container
    MYSQL_DATABASE: {{ .Values.secret.mysql.database }}
    MYSQL_USER: {{ .Values.secret.mysql.user }}
    MYSQL_PASSWORD: {{ .Values.secret.mysql.password }}
    MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysql.rootPassword }}

    #for PHP container
    DB_HOST: {{ .Values.secret.php.dbHost }}
    DB_NAME: {{ .Values.secret.php.dbName }}
    DB_USER: {{ .Values.secret.php.dbUser }}
    DB_PASSWORD: {{ .Values.secret.php.dbPassword }}