apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "php-app.labels" . | nindent 4 }}
spec:
  selector:
    app: php
  ports:
    - port: 80
      targetPort: {{ .Values.php.service.targetPort }}
  type: ClusterIP