nameOveride: ""
fullnameOverride: ""

namespace:
  create: true
  name: "php-app"

php:
  replicaCount: 1
  image:
    repository: "janithad/php-app"
    tag: "latest"
    pullPolicy: "always"
  containerPort: 80
  resources: 
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "300m"
      memory: "256Mi"
  probes:
    path: "/health.pp"
    rediness:
      initialDelaySeconds: 10
      periodSeconds: 5
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 10
  persistence:
    enabled: true
    claimName: "php-pvc"
    size: "5Gi"
    mountPath: "/var/www/html/uploads"
  

mysql:
  replicaCount: 1
  image:
    repository: "mysql"
    tag: "8.0"
    pullPolicy: "IfNotPresent"
  service:
    name: "mysql-service"
    port: 3306
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  persistence:
    enabled: true
    claimName: "mysql-pvc"
    size: "5Gi"

config:
  appEnv: "production"

secret:
  name: "db-secret"
  mysql:
    database: "mydb"
    user: "phpuser"
    password: "password"
    rootPassword: "rootpassword"
  php:
    dbHost: "mysql-service"
    dbName: "mydb"
    dbUser: "phpuser"
    dbPassword: "password"

 